### ISSUE TITLE
Get-AllExOPermissions randomly restarts XLSX output file

### ISSUE THREAD

**Issue by mkoch7811** [jflieben/assortedFunctionsV2#17]
Running Get-AllExOPermissions with no arguments initially creates a roughly 12KB XLSX output file containing all of the Exchange admin roles (on a tab named EXOROLES), then moves on to start processing mailboxes. Our tenant has 15000+ mailboxes, so I just let it run, keeping an eye on the size of the XLSX file. As the script was stepping through the mailboxes, the size of the XLSX file grew. Somewhere around mailbox 1300 out of 15000, the size of the XLSX file suddenly dropped. The file size started growing again, but I stopped the run (Ctrl-C) and when I viewed the contents of the XLSX file, I found that the EXOROLES tab no longer existed, and there was just a Statistics tab and an EXORECIPIENTS tab. I renamed the XLSX file, then re-ran Get-AllExOPermissions. I observed the same behavior at roughly the same point. On a third attempt, I left it run longer and saw the file size reset TWICE. It seems that at some point, the code is overwriting the existing XLSX file, causing all previously written information to be lost.

**Comment by jflieben** [comment]
Thanks for reporting @mkoch7811 , I haven't tested on tenants that size (still waiting for permission). Only has about 1k mailboxes but I think I know what is causing this. The Excel com object probably isn't able to save a file of that size quickly enough, so I will add a file locking and wait mechanism, and ensure data is written in batches instead of once for each mailbox. Expect a fix this or next week.
